# Generated by Django 6.0.2 on 2026-06-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILES_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staff_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
