# Generated by Django 6.0.4 on 2026-04-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILES_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylog',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='working_hours',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
    ]
